title: "Hacking and Coffee"
languageCode: "en-us"
timeZone: "America/Chicago"
theme: "github.com/Hacking-and-Coffee/hackingandcoffee-theme"

ignoreFiles:
  - "content/README\\.md$"
  - "content/.*/README\\.md$"

module:
  hugoVersion:
    extended: true

permalinks:
  posts: /posts/:year/:month/:day/:slug/
  tags: /tags/:slug/
  category: /categories/:slug/
  author: /authors/:slug/
  page: /:slug/
  project: /projects/:slug/
  talk: /talks/:slug/
  artwork: /gallery/:slug/

outputs:
  home: ["HTML", "RSS", "Atom", "JSON"]
  section: ["HTML", "RSS", "Atom", "JSON"]
  taxonomy: ["HTML", "RSS", "Atom", "JSON"]
